max_obstacle_height: 1.6  # assume something like an arm is mounted on top of the robot #0.6

footprint: [[1.5, 0.4],[1.5, -0.4],[-0.4, -0.4], [-0.4, 0.4]]
footprint_padding: 0.05

map_type: costmap

obstacle_layer:
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  max_obstacle_height:  1.6
  unknown_threshold:    15
  mark_threshold:       0
  publish_voxel_map: false
  observation_sources: scan # point_cloud_sensor # scan_cloud rear_scan
  # scan_cloud:
  #   sensor_frame: base_link
  #   data_type: PointCloud2
  #   topic: /scan_cloud  
  #   expected_update_rate: 0.5  # 0.5
  #   marking: true
  #   clearing: true
  #   min_obstacle_height: 0.01    #  0.25 turtlebot_apps, -2.0 jackak
  #   max_obstacle_height: 2      #  0.35 turtlebot_apps,  2.0 jackak 
  #   obstacle_range: 2.5    #  2.5 turtlebot_apps,    
  #   raytrace_range: 3.0    #  3.0 turtlebot_apps,
  scan:
    sensor_frame: first_robot_base_scan
    data_type: LaserScan
    topic: /first_robot/scan
    marking: true
    clearing: true
    obstacle_range: 2.5  #  2.5 turtlebot_apps,
    raytrace_range: 3.0  #  3.0 turtlebot_apps,
    min_obstacle_height: 0.05
    max_obstacle_height: 1.5
  rear_scan:
    data_type: LaserScan
    topic: /second_robot/scan 
    marking: true
    clearing: true
    obstacle_range: 3.0  
    raytrace_range: 3.5 
    min_obstacle_height: 0.05
    max_obstacle_height: 1.5
  # point_cloud_sensor:
  #   sensor_frame: base_link
  #   data_type: PointCloud2
  #   topic: /camera/obstacles_cloud  
  #   expected_update_rate: 2.5  # 0.5
  #   marking: true
  #   clearing: true
  #   max_obstacle_height: 2      #  0.35 turtlebot_apps,  2.0 jackak 
  #   min_obstacle_height: 0.1    #  0.25 turtlebot_apps, -2.0 jackak
  #   obstacle_range: 3.0    #  2.5 turtlebot_apps,    
  #   raytrace_range: 3.5    #  3.0 turtlebot_apps,


inflation_layer:
  enabled: true
  cost_scaling_factor: 25.0 
  inflation_radius: 0.6 
