update_frequency: 5.0
publish_frequency: 1.0
static_map: true
rolling_window: false
resolution: 0.02
transform_tolerance: 0.5
plugins:
  - { name: static_layer, type: "costmap_2d::StaticLayer" }
  - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }  # VoxelLayer
  - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
#  - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }  # VoxelLayer
#  - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
