update_frequency: 10.0   
publish_frequency: 5.0  
# static_map: false
rolling_window: true
width: 8.0
height: 8.0
resolution: 0.02
transform_tolerance: 0.5
footprint_clearing_enabled: true
# inflation_radius: 1.75 
# cost_scaling_factor: 2.58 

plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}   # ObstacleLayer VoxelLayer
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}