max_obstacle_height: 1.6  # assume something like an arm is mounted on top of the robot #0.6

footprint: [[1.5, 0.4],[1.5, -0.4],[-0.4, -0.4], [-0.4, 0.4]]
footprint_padding: 0.05

map_type: costmap

obstacle_layer:
  track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  max_obstacle_height:  1.6
  unknown_threshold:    15
  mark_threshold:       0
  publish_voxel_map: false
  observation_sources: scan 
  scan:
    sensor_frame: first_robot_base_scan
    data_type: LaserScan
    topic: /first_robot/scan
    marking: true
    clearing: true
    obstacle_range: 2.5  #  2.5 turtlebot_apps,
    raytrace_range: 3.0  #  3.0 turtlebot_apps,
    min_obstacle_height: 0.05
    max_obstacle_height: 1.5

inflation_layer:
  enabled: true
  cost_scaling_factor: 25.0 
  inflation_radius: 0.6 
